# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./f1_system.h
SOURCES += ./f1_system.cpp \
    ./main.cpp
FORMS += ./f1_system.ui
RESOURCES += f1_system.qrc
